platform :osx, '10.15'

# CocoaPods analytics sends network stats downstream to the platform to help improve the tool.
# If you don't want to send stats, uncomment the following line.
# install! 'cocoapods', :disable_input_output_paths => true

# The path to the flutter core.
project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
  'Profile' => :profile,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end
